{% set version = "70.0.1" %}

package:
  name: firefox
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/linux-x86_64/en-US/firefox-{{ version }}.tar.bz2  # [linux64]
  sha256: bc1ef29799f15d1fe709a430203d16c12d5ae0899f1c01ba4461062392a2e77e  # [linux64]

  fn: firefox.pkg  # [osx]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/mac/en-US/Firefox%20{{ version }}.pkg  # [osx]
  sha256: 91a1e443f7aa2328386168df98f3c8fc6f57f70d223ca39ecdeeccf6ea9ddfd8  # [osx]

  fn: firefox.msi  # [win]
  url: https://ftp.mozilla.org/pub/firefox/releases/{{ version }}/win64/en-US/Firefox%20Setup%20{{ version }}.msi  # [win]
  sha256: e5b204a843ed0fde0700ba425608c79104e8b62d3b4d1ecd3841e9a2a88a2a1e  # [win]

build:
  number: 0
  binary_relocation:
    - bin/firefox

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  requires:
    - selenium
    - geckodriver

about:
  home: https://www.mozilla.org/en-US/firefox/releases
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'Firefox web browser'

extra:
  recipe-maintainers:
    - birdsarah
    - ocefpaf
