travis:
  secure:
    BINSTAR_TOKEN: rwXn4Z3VEvEeYDgH9Y/jt9IJjiQG/6QzXZsgwDJD/nnO3tmG6iOuavlo0nODizeuFGiDLaTNWxBvhHkPISyqbj7V2KYz9E3s0oFRmUoFqwJe8+GKP2YEyA7GyHUpDy58lwV/3p9yRLPFuMI+Y57ZUVYWiCS1wJHOzWm6fTzCWgK/S/0hjruOURtq58WmNnQ8pRJUxazmvBgsJvmj7vsdZKFWwiqMQZutC/mr4M3QTeRV+FBWc4EzqzJO9V1r28t3T/tJua6wEpP8ukLtKZGozfjIEm+sK7Dc6MVxaMFiTxM4CBw/Z3oTVs1ej3vGMDgs1f4ekTNUyqihP7ucIpHI+ey/nbZRVhw4hSuH4/S3xKLS2a29ivZIDMXKVjCErUspKEVLXErBztpuGqRHXVs2D2pn7kkIREattaEqHIDjJxeUCOxPnMpuXZNXbE7Dr8g8bAajLM2acAqs4DwG+hEHx7pmYOkIPOx6Uhwv1LJ01EnyDMQx9iY/RE5bp4J8WDOsggqDa/dMOL4Rn5aTYAB794eSYM3OHYRoDakJ0JXlpfyz/DSw45MhvUBbifYKCigoCoB6nEcQy3hAGl69Y36RJU3+MMvDqovKySVJXlrd211vWwE0jxR/6UDz4GBYx8lHdbJ8cZeQdgaxKnBg54dt+4Qn6i9FR3VGiJCSC2daGOY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
